// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  hero: dynamic(() => import('./Hero')),
  property: dynamic(() => import('./Property')),
  testimonials: dynamic(() => import('./Testimonials'))
};
