// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  contact_us: dynamic(() => import('./ContactUs')),
  hero: dynamic(() => import('./Hero')),
  property: dynamic(() => import('./Property')),
  property2: dynamic(() => import('./Property2')),
  testimonials: dynamic(() => import('./Testimonials')),
  testing: dynamic(() => import('./Testing'))
};
